# Generated by Django 2.1.3 on 2018-11-26 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptedmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='受付方法')),
            ],
            options={
                'verbose_name': '受付方法',
                'verbose_name_plural': '10受付方法',
            },
        ),
        migrations.CreateModel(
            name='Actioncategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='対応区分')),
            ],
            options={
                'verbose_name': '対応区分',
                'verbose_name_plural': '11対応区分',
            },
        ),
        migrations.CreateModel(
            name='Brmachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='機器名')),
            ],
            options={
                'verbose_name': '機器名',
                'verbose_name_plural': '03機器名',
            },
        ),
        migrations.CreateModel(
            name='Bruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='物件名')),
            ],
            options={
                'verbose_name': '物件名',
                'verbose_name_plural': '02物件名',
            },
        ),
        migrations.CreateModel(
            name='ControlStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='管理情報')),
            ],
            options={
                'verbose_name': '管理情報',
                'verbose_name_plural': '15管理情報',
            },
        ),
        migrations.CreateModel(
            name='Disposalcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='処置区分')),
            ],
            options={
                'verbose_name': '処置区分',
                'verbose_name_plural': '13処置区分',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='製品名')),
            ],
            options={
                'verbose_name': '製品名',
                'verbose_name_plural': '01製品名',
            },
        ),
        migrations.CreateModel(
            name='Suspendcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='停止区分')),
            ],
            options={
                'verbose_name': '停止区分',
                'verbose_name_plural': '12停止区分',
            },
        ),
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='担当者名')),
                ('occurrence_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='発生日時')),
                ('restoration_datetime', models.DateTimeField(blank=True, null=True, verbose_name='復旧日時')),
                ('trouble_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='発生部位')),
                ('error_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='エラーコード')),
                ('error_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='エラー名')),
                ('trouble_name', models.CharField(max_length=50, verbose_name='不具合件名')),
                ('situation', models.TextField(blank=True, max_length=1000, null=True, verbose_name='不具合状況')),
                ('cause', models.TextField(blank=True, max_length=1000, null=True, verbose_name='不具合原因')),
                ('measure', models.TextField(blank=True, max_length=1000, null=True, verbose_name='不具合対策')),
                ('restoration_procedure', models.TextField(blank=True, max_length=1000, null=True, verbose_name='復旧手順')),
                ('special_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='特記事項')),
                ('complete_date', models.DateField(blank=True, null=True, verbose_name='処置完了日')),
                ('field_worker', models.CharField(blank=True, max_length=30, null=True, verbose_name='現地対応者')),
                ('office_worker', models.CharField(blank=True, max_length=20, null=True, verbose_name='社内対応者')),
                ('first_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='１次受付者')),
                ('first_contact_datetime', models.DateTimeField(blank=True, null=True, verbose_name='１次受付日時')),
                ('report_history', models.CharField(blank=True, max_length=10, null=True, verbose_name='客先報告履歴')),
                ('input_date', models.DateField(default=django.utils.timezone.now, verbose_name='入力日')),
                ('inputter', models.CharField(blank=True, max_length=10, null=True, verbose_name='入力者')),
                ('prompt_report', models.BooleanField(default=False, verbose_name='不具合速報F')),
                ('personal_report', models.BooleanField(default=False, verbose_name='個別報告書F')),
                ('supplier_report', models.BooleanField(default=False, verbose_name='不具合連絡票F')),
                ('d32', models.BooleanField(default=False, verbose_name='実施票F')),
                ('related_report', models.BooleanField(default=False, verbose_name='関連報告F')),
                ('trouble_memo', models.TextField(blank=True, max_length=500, null=True, verbose_name='メモ')),
                ('accepted_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trdbapp.Acceptedmethod', verbose_name='受付方法')),
                ('action_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trdbapp.Actioncategory', verbose_name='対応区分')),
                ('control_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trdbapp.ControlStatus', verbose_name='管理情報')),
                ('disposal_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trdbapp.Disposalcategory', verbose_name='処置区分')),
                ('suspend_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trdbapp.Suspendcategory', verbose_name='停止カテゴリ')),
                ('trouble_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trdbapp.Brmachine', verbose_name='不具合機器')),
            ],
            options={
                'verbose_name': '不具合ＤＢ',
                'verbose_name_plural': '99不具合ＤＢ詳細',
            },
        ),
        migrations.CreateModel(
            name='TroubleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='不具合情報')),
            ],
            options={
                'verbose_name': '不具合情報',
                'verbose_name_plural': '14不具合情報',
            },
        ),
        migrations.AddField(
            model_name='trouble',
            name='trouble_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trdbapp.TroubleStatus', verbose_name='不具合情報'),
        ),
        migrations.AddField(
            model_name='trouble',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trdbapp.Bruser', verbose_name='物件名'),
        ),
        migrations.AddField(
            model_name='bruser',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trdbapp.Product', verbose_name='製品名'),
        ),
    ]
